name: CI

on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - 'feature/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configurar entorno con Dev Container
      uses: devcontainers/ci@v0.3
      with:
        runCmd: echo "Entorno listo para evaluación"

    - name: Ejecutar proyecto
      uses: devcontainers/ci@v0.3
      with:
        runCmd: python src/main.py

    - name: Ejecutar pruebas unitarias
      uses: devcontainers/ci@v0.3
      with:
        runCmd: python tests/test_main.py